aws:
  access_key_id: 
  secret_access_key: 
s3:
  region: us-west-2 # S3 bucket region
  buckets:
    jsonpath_assets: iglu-jsonpaths-file # If you have defined your own JSON Schemas, add the s3:// path to your own JSON Path files in your own bucket here
    enriched:
      good: 
        bucket: snowplow-dev-out
        path: enriched/good # This is the same as the :enriched:good: bucket specified for EmrEtlRunner
      archive: 
        bucket: snowplow-dev-archive
        path: storage/enriched # Where to archive enriched events to
download:
  folder: s3Downloads
processed:
  folder: s3Processed
targets:
  - name: "My BigQuery database"
    type: bigquery
    dataset: 
    host: ADD HERE # The endpoint as shown in the Redshift console
    database: ADD HERE # Name of database 
    port: 5439 # Default Redshift port
    table: atomic.events
    username: ADD HERE 
    password: ADD HERE 
    maxerror: 1 # Stop loading on first error, or increase to permit more load errors
    comprows: 200000 # Default for a 1 XL node cluster. Not used unless --include compupdate specified